#made by Elicia Au Duong 01.April.2018

import random

galaxy = {'Phouchg. "We': ['must'],
    'Everything..." said': ['Deep'],
    '"But can': ['you'],
    'front of': ['the'],
    'finally. "But': ['can'],
    'We want': ['you'],
    'licked their': ['dry'],
    'Thought is': ['preparing'],
    "you're going": ['to'],
    '"Yes...!!!...?" "Forty-two,"': ['said'],
    'really not': ['going'],
    'slowly came': ['to'],
    'confirmed Deep': ['Thought.'],
    "moment's expectant": ['pause'],
    'pattern. A': ['soft'],
    'vain. "There': ['really'],
    '"I said': ["I'd"],
    '"Seven and': ['a', 'a'],
    'Deep Thought,': ['"I', '"I', 'and', 'with'],
    'excited children.': ['"And'],
    'with breathless': ['excitement.'],
    'to tell': ['us...."'],
    'Thought computer,"': ['he'],
    '"Now?" "Now,"': ['said'],
    'they said': ['in'],
    'million years': ['later....'],
    "a moment's": ['reflection.', 'expectant'],
    'long gone,': ['but'],
    'at last.': ['"Er..good'],
    'didn\'t I?"': ['[Seven'],
    'impatiently at': ['his'],
    'think about': ['it."', 'it,'],
    'we have': ['designed'],
    'paused. "Yes...!"': ['"Is..."'],
    'is one,"': ['confirmed'],
    'tell us...."': ['he'],
    'as those': ['who'],
    'Thought paused': ['for'],
    'console. Lights': ['flashed'],
    'Great Question..."': ['"Yes..!"'],
    'breathed Phouchg.': ['"There'],
    'to the': ['great', 'Great', 'Galaxy'],
    'I have."': ['The'],
    'They both': ['licked'],
    'breathless excitement.': ['"Yes,"'],
    'continue what': ['they'],
    '"the task': ['we'],
    'a preparation': ['for'],
    'to like': ['it."', 'it,"'],
    '"Yes, I': ['have."'],
    'fidgeted. The': ['tension'],
    'to what?"': ['"Life!"'],
    'last. "Er..good': ['morning,'],
    'trained for': ['this'],
    'Everything? To': ['the'],
    'the Universe,': ['and'],
    'urged Loonsuawl.': ['"I'],
    'the answer,': ['but'],
    'it." ...': ['Fook'],
    'and off': ['experimentally'],
    'said Fook': ['with'],
    '"the answer': ['to'],
    'can you': ['do'],
    '"Doesn\'t matter!"': ['said'],
    'Thought. "Life,': ['the'],
    'Answer to': ['what?"', 'the'],
    'infinite majesty': ['and'],
    'know it!': ['Now!"'],
    'million years...!"': ['they'],
    'into a': ['businesslike'],
    'Deep Thought': ['computer,"', 'paused', 'is', 'at', 'majestically.'],
    'Both of': ['the'],
    'perform is': ['this.'],
    'The tension': ['was'],
    'task we': ['have'],
    'are the': ['ones'],
    '"There is': ['an'],
    'preparing to': ['speak!"'],
    'those who': ['would'],
    'communication channel.': ['"Good'],
    'witness the': ['answer,'],
    'significant pause.': ['"Yes,"'],
    'but even': ['so'],
    'they cried': ['in'],
    'blinked at': ['each'],
    'Question of': ['Life,'],
    'of Life....!"': ['"The'],
    'you to': ['perform', 'tell'],
    'glanced impatiently': ['at'],
    'on the': ['front'],
    'is this.': ['We'],
    'Now..." "All': ['right,"'],
    '"To Everything?': ['To'],
    "But, I'll": ['have'],
    'said Deep': ['Thought.', 'Thought,', 'Thought.', 'Thought.', 'Thought', 'Thought.', 'Thought.', 'Thought.', 'Thought,', 'Thought,'],
    'the ones': ['who'],
    '"Yes," said': ['Deep', 'Deep'],
    '... Fook': ['glanced'],
    'added Deep': ['Thought.'],
    'said finally.': ['"But'],
    'would witness': ['the'],
    'channel. "Good': ['Morning,"'],
    '"Is..." "Yes...!!!...?"': ['"Forty-two,"'],
    'us!" "All': ['right,"'],
    "said I'd": ['have'],
    'so they': ['found'],
    'his watch.': ['"How'],
    '"Of Life,': ['the'],
    'been trained': ['for'],
    'Douglas Adams,': ['The'],
    '"Yes...!" "Is..."': ['said', '"Yes...!!!...?"'],
    'To the': ['great'],
    'descendents continue': ['what'],
    'and Everything..."': ['said'],
    'years later....': ['Fook'],
    'squirming like': ['excited'],
    'Fook and': ['Lunkwill'],
    'said. "Seven': ['and'],
    'not going': ['to'],
    'Answer for': ['you?"'],
    'said Phouchg.': ['"We'],
    'panels slowly': ['came'],
    'who would': ['witness'],
    'designed you': ['to'],
    "I'd have": ['to'],
    'preparation for': ['it,'],
    'of the': ['console.', 'men'],
    'Guide to': ['the'],
    'their lives': ['had'],
    '"Good Morning,"': ['said'],
    'Universe!" said': ['Lunkwill.'],
    '"How long?"': ['he'],
    'gasping and': ['squirming'],
    'on and': ['off'],
    'this. We': ['want'],
    'have." The': ['two'],
    'majestically. "Yes,': ['I'],
    'he said.': ['"Seven'],
    '"Now?" inquired': ['Deep'],
    'Lights flashed': ['on'],
    'dry lips.': ['"Though'],
    'everything?" "Yes."': ['Both'],
    'the Great': ['Question..."'],
    'off experimentally': ['and'],
    'they started]': ['"We'],
    '"do you': ['have...er,'],
    'said Loonquawl.': ['"And'],
    'it! Now!"': ['"Now?"'],
    'to think': ['about', 'about'],
    'Loonquawl nervously,': ['"do'],
    'their dry': ['lips.'],
    'flashed on': ['and'],
    'it," observed': ['Deep'],
    'experimentally and': ['settled'],
    "I don't": ['think,"'],
    'each other.': ['"Seven'],
    'men shivered': ['with'],
    'settled down': ['into'],
    'like it."': ['"Doesn\'t'],
    'one?" breathed': ['Phouchg.'],
    'Now!" "Now?"': ['inquired'],
    'Loonquawl. "And': ['Everything...!"'],
    'Lunkwill. "Everything!"': ['they'],
    'tension was': ['unbearable.'],
    'settled into': ['silence'],
    'for it,': ['they'],
    "moment's reflection.": ['"Tricky,"'],
    'said, "the': ['task'],
    'said Lunkwill.': ['"Everything!"'],
    'in vain.': ['"There'],
    '"Yes..!" "Of': ['Life,'],
    'selected at': ['birth'],
    'while panels': ['slowly'],
    '"And you\'re': ['ready'],
    '"The Answer."': ['"The'],
    'both licked': ['their'],
    'the men': ['had'],
    'Thought at': ['last.'],
    'it to': ['us?"'],
    'silence again.': ['The'],
    'can do': ['it."'],
    'answer. But,': ["I'll"],
    'declaimed Deep': ['Thought,'],
    'is an': ['answer?"', 'answer.'],
    'life on': ['the'],
    'was a': ["moment's"],
    'found themselves': ['gasping'],
    'he said': ['finally.'],
    'speak!" There': ['was'],
    'Loonquawl with': ['a'],
    'he said,': ['"the'],
    "it, didn't": ['I?"'],
    'one," confirmed': ['Deep'],
    'other. "Seven': ['and'],
    'There was': ['a'],
    'answer, but': ['even'],
    '[Seven and': ['a'],
    '"Life!" urged': ['Fook.'],
    'you?" interrupted': ['Deep'],
    'and a': ['half', 'half', 'half'],
    '"Though I': ["don't"],
    'Fook with': ['breathless'],
    '"Shhh," said': ['Loonquawl'],
    'I?" [Seven': ['and'],
    'to give': ['it'],
    'and settled': ['down', 'into'],
    'at his': ['watch.'],
    'inquired Deep': ['Thought.'],
    'with infinite': ['majesty'],
    'will hear,"': ['said'],
    'Universe, and': ['Everything.'],
    'Fook blinked': ['at'],
    '"Yes." Both': ['of'],
    'and calm.': ['-'],
    'for a': ["moment's"],
    '"Er..good morning,': ['O'],
    'said in': ['chorus.'],
    'excitement. "Yes,"': ['said'],
    'great Question': ['of'],
    'their descendents': ['continue'],
    'an answer.': ['But,'],
    'about it,': ["didn't"],
    'computer," he': ['said,'],
    'cried in': ['chorus.'],
    '"Yes! Now..."': ['"All'],
    'chorus. "Yes,"': ['declaimed'],
    'morning, O': ['Deep'],
    'said Phouchg,': ['"the'],
    'is..." "An': ['Answer'],
    'Thought, and': ['paused.'],
    '"I can': ['do'],
    'years...!" they': ['cried'],
    '"We are': ['the'],
    '"Yes," declaimed': ['Deep'],
    '"And Everything...!"': ['"Shhh,"'],
    'majesty and': ['calm.'],
    'Phouchg, "the': ['answer'],
    'but their': ['descendents'],
    'a significant': ['pause.'],
    'Thought. "The': ['Answer', 'Answer'],
    'was unbearable.': ['"You\'re'],
    'low hum': ['came'],
    'have to': ['think', 'think'],
    'years," said': ['Deep'],
    'it." "There': ['is'],
    'themselves gasping': ['and'],
    'Their waiting': ['had'],
    'Answer." "The': ['Answer?"'],
    "The Hitchhiker's": ['Guide'],
    'Fook. "The': ['Universe!"'],
    'even so': ['they'],
    'question of': ['Life....!"'],
    'There is': ['an'],
    '"The Universe!"': ['said'],
    'Thought, with': ['infinite'],
    'the great': ['question', 'Question'],
    '"An Answer': ['for'],
    'right," said': ['the', 'Deep'],
    'Loonsuawl. "I': ['am."'],
    'Everything...!" "Shhh,"': ['said'],
    'gone, but': ['their'],
    'computer, and': ['settled'],
    'great question': ['of'],
    'expectant pause': ['while'],
    'are long': ['gone,'],
    'pause while': ['panels'],
    'shivered with': ['expectancy.'],
    '"O Deep': ['Thought'],
    '"that you\'re': ['going'],
    '"All right,"': ['said', 'said'],
    '"The Answer?"': ['said'],
    'Thought. Lunkwill': ['and'],
    'watch. "How': ['long?"'],
    'answer?" said': ['Fook'],
    'Answer?" said': ['Deep'],
    'been a': ['preparation'],
    'unbearable. "You\'re': ['really'],
    'a half': ['million', 'million', 'million'],
    'who will': ['hear,"'],
    'it." "Doesn\'t': ['matter!"'],
    'Adams, The': ["Hitchhiker's"],
    'came from': ['the'],
    'have designed': ['you'],
    'said the': ['computer,'],
    'Lunkwill and': ['Fook'],
    '"Now," said': ['Deep'],
    'answer to': ['the'],
    'men had': ['been'],
    'hear," said': ['Phouchg,'],
    'reflection. "Tricky,"': ['he'],
    'had been': ['trained', 'a', 'selected'],
    'Again, a': ['significant'],
    'Deep Thought.': ['"The', '"Life,', 'Lunkwill', '"To', 'They', '"that', '"Yes!', '"Tell', '"The', '"Yes...!"'],
    'Thought" said': ['Loonquawl'],
    'Thought. They': ['both'],
    'from the': ['communication'],
    'an answer?"': ['said'],
    'waiting had': ['not'],
    'soft low': ['hum'],
    '"Everything!" they': ['said'],
    'this moment,': ['their'],
    '"The Answer': ['to', 'to'],
    'The two': ['men', 'men'],
    'lips. "Though': ['I'],
    '"I am."': ['"Now?"'],
    'Life, the': ['Universe', 'Universe'],
    'birth as': ['those'],
    'for you?"': ['interrupted'],
    'businesslike pattern.': ['A'],
    "Hitchhiker's Guide": ['to'],
    'is preparing': ['to'],
    'Phouchg. "There': ['really'],
    'started] "We': ['are'],
    'came to': ['life'],
    'paused for': ['a'],
    'the front': ['of'],
    'pause. "Yes,"': ['said'],
    'matter!" said': ['Phouchg.'],
    '"Forty-two," said': ['Deep'],
    'been selected': ['at'],
    'interrupted Deep': ['Thought'],
    'the console.': ['Lights'],
    'Universe...!" said': ['Loonquawl.'],
    'later.... Fook': ['and'],
    '"Tricky," he': ['said'],
    '"Is..." said': ['Deep'],
    'really is': ['one?"', 'one,"'],
    'O Deep': ['Thought"'],
    'a businesslike': ['pattern.'],
    'ones who': ['will'],
    'urged Fook.': ['"The'],
    'been in': ['vain.'],
    'Fook glanced': ['impatiently'],
    'that is..."': ['"An'],
    'am." "Now?"': ['"Now,"'],
    'again. The': ['two'],
    'they found': ['themselves'],
    'said Loonquawl': ['with', 'nervously,'],
    'Thought majestically.': ['"Yes,'],
    'the Universe': ['and', 'and'],
    'Universe and': ['everything?"', 'Everything..."'],
    'do it."': ['"There'],
    'not been': ['in'],
    '"The Universe...!"': ['said'],
    'do it?"': ['Again,'],
    'about it."': ['...'],
    'what?" "Life!"': ['urged'],
    'must know': ['it!'],
    'you do': ['it?"'],
    'to speak!"': ['There'],
    'like excited': ['children.'],
    'the communication': ['channel.'],
    "you're ready": ['to'],
    '"You\'re really': ['not'],
    'at each': ['other.'],
    'ready to': ['give'],
    'two men': ['shivered', 'fidgeted.'],
    'us...." he': ['paused,'],
    'with a': ['slight'],
    'Morning," said': ['Deep'],
    'into silence': ['again.'],
    'in chorus.': ['Deep', '"Yes,"'],
    '- Douglas': ['Adams,'],
    'Everything. There': ['is'],
    'moment, their': ['lives'],
    'million years,"': ['said'],
    'hum came': ['from'],
    'to us?"': ['urged'],
    'to life': ['on'],
    'Thought. "that': ["you're"],
    'the computer,': ['and'],
    'he paused,': ['"The'],
    '"We must': ['know'],
    'to perform': ['is'],
    'is one?"': ['breathed'],
    'a slight': ['gesture.'],
    'nervously, "do': ['you'],
    'Lunkwill are': ['long'],
    '"Tell us!"': ['"All'],
    'at birth': ['as'],
    'think Deep': ['Thought'],
    'and Lunkwill': ['are'],
    'gesture. "I': ['think'],
    '"Life, the': ['Universe,'],
    'Thought, "I': ['can', 'said'],
    'children. "And': ["you're"],
    'like it,"': ['observed'],
    'for this': ['moment,'],
    'and Fook': ['blinked'],
    'it, they': ['had'],
    'Thought. "Yes...!"': ['"Is..."'],
    'going to': ['like', 'like'],
    'and squirming': ['like'],
    ' "O': ['Deep'],
    'us?" urged': ['Loonsuawl.'],
    'and paused.': ['"Yes...!"'],
    'Thought. "To': ['Everything?'],
    'long?" he': ['said.'],
    "I'll have": ['to'],
    'Question..." "Yes..!"': ['"Of'],
    'of Life,': ['the'],
    'half million': ['years,"', 'years...!"', 'years'],
    'give it': ['to'],
    'Life....!" "The': ['Universe...!"'],
    'lives had': ['been'],
    'and everything?"': ['"Yes."'],
    'observed Deep': ['Thought.'],
    'Deep Thought"': ['said'],
    'with expectancy.': ['Their'],
    'want you': ['to'],
    'chorus. Deep': ['Thought'],
    '"There really': ['is', 'is'],
    'calm. -': ['Douglas'],
    'A soft': ['low'],
    'slight gesture.': ['"I'],
    'it?" Again,': ['a'],
    'they had': ['been'],
    'down into': ['a'],
    'think," added': ['Deep'],
    'you have...er,': ['that'],
    'what they': ['started]'],
    '"I think': ['Deep'],
    'don\'t think,"': ['added'],
    'had not': ['been'],
    'Thought. "Yes!': ['Now..."'],
    'and Everything.': ['There'],
    'have...er, that': ['is..."'],
    'Thought. "Tell': ['us!"'],
    'men fidgeted.': ['The'],
    'paused, "The': ['Answer."'],
    'expectancy. Their': ['waiting']}

print("I am a markov chain generator")
current_word = input("What words do you want to start with? ")
story = current_word
correct = "no"
while correct == "no":
    if current_word in galaxy:
        for i in range(200):
            next_word_options = galaxy[current_word]
            next_word = random.choice(next_word_options)
            story = story + " " + next_word
            lines = story.split()
            two_words = lines[-2:]
            next_two = " ".join(two_words)
            #print(next_two)
            current_word = next_two
        print(story)
        correct = "yes"
    else:
        print("Sorry, you can't use that as a starting word!")
        current_word = input("What words do you want to start with? ")